INFO 2020-07-25 05:15:13,630 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-25 09:20:03,977 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-25 09:24:05,858 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-07-25 09:27:49,134 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-25 09:29:20,761 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-25 09:34:09,096 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-25 09:34:39,651 basehttp 154 "GET / HTTP/1.1" 200 16348
INFO 2020-07-25 09:34:45,735 basehttp 154 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2020-07-25 09:34:47,612 basehttp 154 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2020-07-25 09:34:47,647 basehttp 154 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
INFO 2020-07-25 09:34:47,669 basehttp 154 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
WARNING 2020-07-25 09:34:48,271 log 228 Not Found: /favicon.ico
WARNING 2020-07-25 09:34:48,286 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 1977
INFO 2020-07-25 09:57:33,473 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2020-07-25 09:57:38,244 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-25 09:58:58,993 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2020-07-25 09:58:59,300 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-25 10:18:45,263 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2020-07-25 10:18:45,750 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-25 10:21:56,976 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2020-07-25 10:21:57,283 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-25 10:22:41,707 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2020-07-25 10:22:42,015 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-25 10:25:05,880 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-07-25 10:25:06,269 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-25 12:13:46,930 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-07-25 12:16:34,933 exception 77 Invalid HTTP_HOST header: 'www.meiduo.site:8000'. You may need to add 'www.meiduo.site' to ALLOWED_HOSTS.
WARNING 2020-07-25 12:16:35,198 log 228 Bad Request: /carts/simple/
WARNING 2020-07-25 12:16:35,201 basehttp 154 "GET /carts/simple/ HTTP/1.1" 400 66977
ERROR 2020-07-25 12:16:54,145 exception 77 Invalid HTTP_HOST header: 'www.meiduo.site:8000'. You may need to add 'www.meiduo.site' to ALLOWED_HOSTS.
WARNING 2020-07-25 12:16:54,205 log 228 Bad Request: /carts/simple/
WARNING 2020-07-25 12:16:54,206 basehttp 154 "GET /carts/simple/ HTTP/1.1" 400 66977
ERROR 2020-07-25 12:17:12,731 exception 77 Invalid HTTP_HOST header: 'www.meiduo.site:8000'. You may need to add 'www.meiduo.site' to ALLOWED_HOSTS.
WARNING 2020-07-25 12:17:12,870 log 228 Bad Request: /carts/simple/
WARNING 2020-07-25 12:17:12,876 basehttp 154 "GET /carts/simple/ HTTP/1.1" 400 66977
ERROR 2020-07-25 12:17:14,067 exception 77 Invalid HTTP_HOST header: 'www.meiduo.site:8000'. You may need to add 'www.meiduo.site' to ALLOWED_HOSTS.
WARNING 2020-07-25 12:17:14,145 log 228 Bad Request: /image_codes/cdeff2b0-e3e5-4d62-9925-5e137488f042/
WARNING 2020-07-25 12:17:14,159 basehttp 154 "GET /image_codes/cdeff2b0-e3e5-4d62-9925-5e137488f042/ HTTP/1.1" 400 67254
ERROR 2020-07-25 12:17:27,853 exception 77 Invalid HTTP_HOST header: 'www.meiduo.site:8000'. You may need to add 'www.meiduo.site' to ALLOWED_HOSTS.
WARNING 2020-07-25 12:17:27,893 log 228 Bad Request: /usernames/liyiqi/count/
WARNING 2020-07-25 12:17:27,894 basehttp 154 "GET /usernames/liyiqi/count/ HTTP/1.1" 400 67100
ERROR 2020-07-25 12:17:40,102 exception 77 Invalid HTTP_HOST header: 'www.meiduo.site:8000'. You may need to add 'www.meiduo.site' to ALLOWED_HOSTS.
WARNING 2020-07-25 12:17:40,138 log 228 Bad Request: /usernames/liyiqi/count/
WARNING 2020-07-25 12:17:40,141 basehttp 154 "GET /usernames/liyiqi/count/ HTTP/1.1" 400 67100
ERROR 2020-07-25 12:17:40,142 basehttp 154 "GET /usernames/liyiqi/count/ HTTP/1.1" 500 59
INFO 2020-07-25 12:22:52,941 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-07-25 12:22:56,812 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-25 12:23:22,506 log 228 Not Found: /
WARNING 2020-07-25 12:23:22,515 basehttp 154 "GET / HTTP/1.1" 404 2312
WARNING 2020-07-25 12:23:22,845 log 228 Not Found: /favicon.ico
WARNING 2020-07-25 12:23:22,847 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2363
INFO 2020-07-25 12:23:41,580 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-25 12:23:50,054 log 228 Not Found: /carts/simple/
WARNING 2020-07-25 12:23:50,055 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2375
WARNING 2020-07-25 12:23:54,777 log 228 Not Found: /
WARNING 2020-07-25 12:23:54,781 basehttp 154 "GET / HTTP/1.1" 404 2312
WARNING 2020-07-25 12:24:02,883 log 228 Not Found: /carts/simple/
WARNING 2020-07-25 12:24:02,885 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2375
WARNING 2020-07-25 12:25:04,309 log 228 Not Found: /register.html
WARNING 2020-07-25 12:25:04,316 basehttp 154 "GET /register.html HTTP/1.1" 404 2369
WARNING 2020-07-25 12:25:40,161 log 228 Not Found: /register.html
WARNING 2020-07-25 12:25:40,161 basehttp 154 "GET /register.html HTTP/1.1" 404 2369
INFO 2020-07-27 01:14:19,817 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-27 01:14:55,696 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-27 01:15:14,641 log 228 Not Found: /
WARNING 2020-07-27 01:15:14,643 basehttp 154 "GET / HTTP/1.1" 404 2314
WARNING 2020-07-27 01:15:14,887 log 228 Not Found: /favicon.ico
WARNING 2020-07-27 01:15:14,890 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2365
INFO 2020-07-27 03:55:13,212 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/urls.py changed, reloading.
INFO 2020-07-27 03:55:14,056 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-27 04:00:13,088 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/urls.py changed, reloading.
INFO 2020-07-27 04:00:14,832 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-27 04:12:21,689 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/urls.py changed, reloading.
INFO 2020-07-27 04:12:23,625 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-27 04:25:17,224 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/urls.py changed, reloading.
INFO 2020-07-27 04:25:18,941 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-27 05:50:23,811 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-07-27 05:50:24,522 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-27 05:50:34,034 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-07-27 05:50:34,640 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-27 05:52:21,573 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-27 05:54:08,151 basehttp 154 "GET /image_codes/5e116f4e-6bbb-4f1a-a2c2-6a3caca7d280/ HTTP/1.1" 200 3068
INFO 2020-07-27 05:54:32,885 basehttp 154 "GET /image_codes/f167d04c-9691-44ed-bc65-6dda17f16310/ HTTP/1.1" 200 3403
INFO 2020-07-27 05:54:42,370 basehttp 154 "GET /image_codes/259b65c6-212e-46e3-b605-0fb9f978c258/ HTTP/1.1" 200 3034
INFO 2020-07-27 07:06:38,941 basehttp 154 "GET /image_codes/5ab3fc85-d21d-4975-ba09-96c92611ad84/ HTTP/1.1" 200 3069
INFO 2020-07-27 07:06:54,193 basehttp 154 "GET /image_codes/5a02337c-08a7-4203-884a-5b0465ef8f5e/ HTTP/1.1" 200 2686
INFO 2020-07-27 11:58:19,440 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-27 11:59:24,019 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-27 12:00:02,780 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-27 12:00:22,050 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-27 12:03:26,536 log 228 Not Found: /
WARNING 2020-07-27 12:03:26,567 basehttp 154 "GET / HTTP/1.1" 404 2686
WARNING 2020-07-27 12:03:27,259 log 228 Not Found: /favicon.ico
WARNING 2020-07-27 12:03:27,269 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2737
WARNING 2020-07-27 12:03:32,705 log 228 Not Found: /
WARNING 2020-07-27 12:03:32,707 basehttp 154 "GET / HTTP/1.1" 404 2686
WARNING 2020-07-27 12:04:52,027 log 228 Not Found: /carts/simple/
WARNING 2020-07-27 12:04:52,032 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2749
INFO 2020-07-27 12:04:56,426 basehttp 154 "GET /image_codes/d4aee648-1cd5-442f-83b2-89a26ca89ff1/ HTTP/1.1" 200 3011
INFO 2020-07-27 12:05:15,160 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-27 12:05:15,180 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-27 12:05:15,496 basehttp 154 "GET /sms_codes/13242327249/?image_code=eduf&image_code_id=d4aee648-1cd5-442f-83b2-89a26ca89ff1 HTTP/1.1" 200 61
INFO 2020-07-27 12:05:40,747 basehttp 154 "GET /image_codes/4481e311-1a90-4981-81b9-0361ebca9724/ HTTP/1.1" 200 3238
INFO 2020-07-27 12:57:36,387 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-07-27 12:57:41,483 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-27 12:57:47,660 basehttp 154 "GET /mobiles/13133113311/count/ HTTP/1.1" 200 39
INFO 2020-07-27 12:58:02,165 basehttp 154 "GET /image_codes/d9db736d-c665-4c21-b81b-a511076a0c3d/ HTTP/1.1" 200 3257
INFO 2020-07-27 12:58:07,918 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-27 12:58:11,813 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-27 12:58:12,092 basehttp 154 "GET /sms_codes/13242327249/?image_code=VNRD&image_code_id=d9db736d-c665-4c21-b81b-a511076a0c3d HTTP/1.1" 200 61
INFO 2020-07-29 04:44:28,343 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-29 05:47:26,870 log 228 Not Found: /
WARNING 2020-07-29 05:47:26,881 basehttp 154 "GET / HTTP/1.1" 404 2686
WARNING 2020-07-29 05:47:27,171 log 228 Not Found: /favicon.ico
WARNING 2020-07-29 05:47:27,184 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2737
WARNING 2020-07-29 05:50:16,043 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 05:50:16,045 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2749
WARNING 2020-07-29 05:50:24,619 log 228 Not Found: /
WARNING 2020-07-29 05:50:24,635 basehttp 154 "GET / HTTP/1.1" 404 2686
WARNING 2020-07-29 05:50:25,825 log 228 Not Found: /favicon.ico
WARNING 2020-07-29 05:50:25,834 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2737
ERROR 2020-07-29 05:50:52,519 exception 77 Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2020-07-29 05:50:52,664 log 228 Bad Request: /
WARNING 2020-07-29 05:50:52,676 basehttp 154 "GET / HTTP/1.1" 400 67680
ERROR 2020-07-29 05:50:53,105 exception 77 Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2020-07-29 05:50:53,297 log 228 Bad Request: /favicon.ico
WARNING 2020-07-29 05:50:53,298 basehttp 154 "GET /favicon.ico HTTP/1.1" 400 67723
WARNING 2020-07-29 05:52:35,341 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 05:52:35,342 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2749
INFO 2020-07-29 05:52:46,409 basehttp 154 "GET /image_codes/5705c310-d64a-40c6-baa3-f1329738a82d/ HTTP/1.1" 200 3357
INFO 2020-07-29 06:16:34,083 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-07-29 06:16:37,586 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 06:16:47,047 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:17:15,723 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:17:26,655 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
ERROR 2020-07-29 06:17:26,742 log 228 Internal Server Error: /sms_codes/13242327249/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 86, in get
    image_code_server = image_code_server.decode()
AttributeError: 'NoneType' object has no attribute 'decode'
ERROR 2020-07-29 06:17:26,746 basehttp 154 "GET /sms_codes/13242327249/?image_code=bkus&image_code_id=5705c310-d64a-40c6-baa3-f1329738a82d HTTP/1.1" 500 82305
INFO 2020-07-29 06:19:15,606 basehttp 154 "GET /image_codes/553d94bf-ed6b-46eb-9f4e-7dc8a182686d/ HTTP/1.1" 200 3324
INFO 2020-07-29 06:19:21,602 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:19:21,870 basehttp 154 "GET /sms_codes/13242327249/?image_code=yecf&image_code_id=553d94bf-ed6b-46eb-9f4e-7dc8a182686d HTTP/1.1" 200 61
INFO 2020-07-29 06:19:54,855 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2020-07-29 06:19:54,880 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:19:54,893 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
WARNING 2020-07-29 06:19:54,926 log 228 Forbidden (CSRF cookie not set.): /register/
WARNING 2020-07-29 06:19:54,927 basehttp 154 "POST /register/ HTTP/1.1" 403 2868
WARNING 2020-07-29 06:19:57,914 log 228 Forbidden (CSRF cookie not set.): /register/
INFO 2020-07-29 06:19:57,914 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:19:57,922 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
WARNING 2020-07-29 06:19:57,930 basehttp 154 "POST /register/ HTTP/1.1" 403 2868
WARNING 2020-07-29 06:19:59,490 log 228 Forbidden (CSRF cookie not set.): /register/
WARNING 2020-07-29 06:19:59,491 basehttp 154 "POST /register/ HTTP/1.1" 403 2868
INFO 2020-07-29 06:19:59,503 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:19:59,506 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
WARNING 2020-07-29 06:19:59,641 log 228 Forbidden (CSRF cookie not set.): /register/
WARNING 2020-07-29 06:19:59,653 basehttp 154 "POST /register/ HTTP/1.1" 403 2868
INFO 2020-07-29 06:19:59,663 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:19:59,669 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
WARNING 2020-07-29 06:20:09,333 log 228 Forbidden (CSRF cookie not set.): /register/
WARNING 2020-07-29 06:20:09,339 basehttp 154 "POST /register/ HTTP/1.1" 403 2868
INFO 2020-07-29 06:20:09,350 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:20:09,360 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
WARNING 2020-07-29 06:20:16,928 log 228 Forbidden (CSRF cookie not set.): /register/
WARNING 2020-07-29 06:20:16,934 basehttp 154 "POST /register/ HTTP/1.1" 403 2868
INFO 2020-07-29 06:20:16,958 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:20:16,965 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
WARNING 2020-07-29 06:20:38,902 log 228 Forbidden (CSRF cookie not set.): /register/
WARNING 2020-07-29 06:20:38,906 basehttp 154 "POST /register/ HTTP/1.1" 403 2868
INFO 2020-07-29 06:20:38,950 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:20:38,977 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:21:18,127 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-07-29 06:21:18,956 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 06:22:13,599 basehttp 154 "GET /image_codes/edbcbcb5-8d73-4b4e-9ed2-2ab436a209cb/ HTTP/1.1" 200 3098
INFO 2020-07-29 06:22:17,339 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:22:28,895 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:22:31,657 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:22:32,544 basehttp 154 "GET /image_codes/4e2d3927-6999-471a-82a4-9679422f14f4/ HTTP/1.1" 200 3372
INFO 2020-07-29 06:22:38,198 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:22:38,386 basehttp 154 "GET /sms_codes/13242327249/?image_code=oyhr&image_code_id=4e2d3927-6999-471a-82a4-9679422f14f4 HTTP/1.1" 200 61
INFO 2020-07-29 06:23:11,732 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:23:11,739 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:23:11,936 basehttp 154 "POST /register/ HTTP/1.1" 200 27
WARNING 2020-07-29 06:23:12,691 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 06:23:12,694 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
INFO 2020-07-29 06:26:27,011 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 06:26:29,279 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 06:27:26,587 basehttp 154 "GET /image_codes/641a80cb-1418-4dcd-ad85-b2a3fa37c690/ HTTP/1.1" 200 3198
INFO 2020-07-29 06:27:27,399 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:27:31,673 basehttp 154 "GET /usernames/lijie2/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:27:40,609 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:27:40,651 basehttp 154 "GET /image_codes/07ace06c-5917-41e2-a2ff-1b93c35f83b9/ HTTP/1.1" 200 2851
INFO 2020-07-29 06:27:51,377 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:27:51,661 basehttp 154 "GET /sms_codes/13242327249/?image_code=A4fc&image_code_id=07ace06c-5917-41e2-a2ff-1b93c35f83b9 HTTP/1.1" 200 61
INFO 2020-07-29 06:28:06,536 basehttp 154 "GET /usernames/lijie2/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:28:06,590 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:28:06,746 basehttp 154 "POST /register/ HTTP/1.1" 200 27
WARNING 2020-07-29 06:28:07,435 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 06:28:07,436 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
INFO 2020-07-29 06:30:33,137 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 06:30:34,022 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 06:30:59,464 basehttp 154 "GET /image_codes/a2515c3c-3b32-4d67-b4ec-10676bed8e9d/ HTTP/1.1" 200 3360
INFO 2020-07-29 06:31:03,609 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:31:06,296 basehttp 154 "GET /usernames/lijie3/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:31:14,206 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:31:14,253 basehttp 154 "GET /image_codes/393854d3-21b8-49cd-ae64-21990f568443/ HTTP/1.1" 200 3161
INFO 2020-07-29 06:31:19,632 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:31:19,879 basehttp 154 "GET /sms_codes/13242327249/?image_code=tlrc&image_code_id=393854d3-21b8-49cd-ae64-21990f568443 HTTP/1.1" 200 61
INFO 2020-07-29 06:31:39,604 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:31:39,636 basehttp 154 "GET /usernames/lijie3/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:31:39,676 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2020-07-29 06:31:39,830 basehttp 154 "POST /register/ HTTP/1.1" 200 75
INFO 2020-07-29 06:31:51,274 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:32:14,693 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:32:14,750 basehttp 154 "GET /usernames/lijie3/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:32:14,756 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:32:14,930 basehttp 154 "POST /register/ HTTP/1.1" 200 27
WARNING 2020-07-29 06:32:15,587 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 06:32:15,587 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
INFO 2020-07-29 06:33:07,022 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-07-29 06:33:08,340 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 06:39:58,252 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 06:39:59,310 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 06:40:01,894 basehttp 154 "GET /image_codes/3bb6d363-e06c-4c7d-9715-3a777d245445/ HTTP/1.1" 200 2978
INFO 2020-07-29 06:40:02,529 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:40:07,441 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:40:13,298 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:40:13,344 basehttp 154 "GET /image_codes/535cac05-bb00-4c95-90e8-55a069f81591/ HTTP/1.1" 200 3141
INFO 2020-07-29 06:40:17,323 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:40:17,524 basehttp 154 "GET /sms_codes/13242327249/?image_code=dxhi&image_code_id=535cac05-bb00-4c95-90e8-55a069f81591 HTTP/1.1" 200 61
WARNING 2020-07-29 06:40:52,111 log 228 Forbidden (CSRF cookie not set.): /register/
WARNING 2020-07-29 06:40:52,112 basehttp 154 "POST /register/ HTTP/1.1" 403 2868
INFO 2020-07-29 06:40:52,130 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:40:52,132 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:41:35,463 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-07-29 06:41:36,189 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 06:41:36,649 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:41:36,652 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:41:36,703 basehttp 154 "POST /register/ HTTP/1.1" 200 27
WARNING 2020-07-29 06:41:37,349 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 06:41:37,350 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
INFO 2020-07-29 06:54:19,890 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 06:54:22,092 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 06:54:24,151 basehttp 154 "GET /image_codes/fac5b635-5596-4330-b803-9776f097efbe/ HTTP/1.1" 200 2881
INFO 2020-07-29 06:54:24,900 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:54:27,029 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:54:29,655 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:54:29,733 basehttp 154 "GET /image_codes/7774b4a5-06af-455a-bf6f-556e11afc107/ HTTP/1.1" 200 3021
INFO 2020-07-29 06:54:32,124 basehttp 154 "GET /image_codes/66a7dfd8-40c3-4658-b09b-56d2855751e4/ HTTP/1.1" 200 3176
INFO 2020-07-29 06:54:39,031 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:54:39,138 basehttp 154 "GET /sms_codes/13242327249/?image_code=cxhp&image_code_id=66a7dfd8-40c3-4658-b09b-56d2855751e4 HTTP/1.1" 200 61
INFO 2020-07-29 06:54:56,044 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:54:56,059 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2020-07-29 06:54:56,072 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 06:54:56,214 basehttp 154 "POST /register/ HTTP/1.1" 200 27
WARNING 2020-07-29 06:54:57,677 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 06:54:57,680 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
WARNING 2020-07-29 06:56:24,599 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 06:56:24,603 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
INFO 2020-07-29 06:56:58,229 basehttp 154 "GET /image_codes/ad36cbb5-e2bc-4418-9e5a-b34ed8b83798/ HTTP/1.1" 200 3162
WARNING 2020-07-29 06:57:20,580 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 06:57:20,581 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
INFO 2020-07-29 06:57:23,260 basehttp 154 "GET /image_codes/91a94fba-5eac-4a2d-ab90-607f0cc60b4c/ HTTP/1.1" 200 3402
INFO 2020-07-29 06:57:29,071 basehttp 154 "GET /image_codes/79c46b97-26fb-4aa0-b96f-9635de60e8b4/ HTTP/1.1" 200 3713
WARNING 2020-07-29 06:57:33,842 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 06:57:33,848 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
INFO 2020-07-29 06:57:34,449 basehttp 154 "GET /image_codes/bd9bc591-532c-4e59-936f-c415259425e6/ HTTP/1.1" 200 3409
WARNING 2020-07-29 06:57:40,174 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 06:57:40,178 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
INFO 2020-07-29 06:57:44,887 basehttp 154 "GET /image_codes/bd9bc591-532c-4e59-936f-c415259425e6/ HTTP/1.1" 200 3796
INFO 2020-07-29 06:59:06,828 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-07-29 06:59:08,265 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 06:59:47,922 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-07-29 06:59:48,592 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:00:34,210 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-29 07:01:04,140 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 07:01:04,140 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
INFO 2020-07-29 07:01:04,371 basehttp 154 "GET /image_codes/16962306-2825-4240-913a-5ccbcc378919/ HTTP/1.1" 200 3108
INFO 2020-07-29 07:01:06,165 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 07:01:40,374 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 07:01:49,972 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 07:01:50,044 basehttp 154 "GET /image_codes/884b4267-0f24-484b-b139-9bbb1d69c608/ HTTP/1.1" 200 3264
INFO 2020-07-29 07:01:55,802 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 07:01:55,926 basehttp 154 "GET /sms_codes/13242327249/?image_code=icra&image_code_id=884b4267-0f24-484b-b139-9bbb1d69c608 HTTP/1.1" 200 61
INFO 2020-07-29 07:02:13,006 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2020-07-29 07:02:13,021 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 07:02:13,024 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-29 07:02:13,046 basehttp 154 "POST /register/ HTTP/1.1" 200 27
WARNING 2020-07-29 07:02:13,387 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 07:02:13,388 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
WARNING 2020-07-29 07:02:31,324 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 07:02:31,324 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
WARNING 2020-07-29 07:04:41,002 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 07:04:41,007 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
WARNING 2020-07-29 07:04:57,286 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 07:04:57,287 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
INFO 2020-07-29 07:05:09,111 basehttp 154 "GET /image_codes/fe415f12-853a-41f2-8886-303c5ef6741a/ HTTP/1.1" 200 3566
INFO 2020-07-29 07:05:11,525 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-29 07:05:17,391 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
WARNING 2020-07-29 07:07:31,666 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 07:07:31,667 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2905
INFO 2020-07-29 07:27:09,977 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-07-29 07:27:13,649 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:31:48,945 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 07:31:53,165 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-29 07:32:37,840 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 07:32:37,843 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
WARNING 2020-07-29 07:32:48,664 log 228 Not Found: /carts/simple/
WARNING 2020-07-29 07:32:48,666 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-07-29 07:32:50,659 basehttp 154 "GET /image_codes/3c7cb4a2-588c-478f-8216-b576af18feea/ HTTP/1.1" 200 3252
INFO 2020-07-29 07:33:12,593 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 07:33:13,411 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:33:27,348 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
ERROR 2020-07-29 07:33:27,438 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py", line 166, in post
    login(request,user)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 126, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
ERROR 2020-07-29 07:33:27,440 basehttp 154 "POST /login/ HTTP/1.1" 500 89240
INFO 2020-07-29 07:35:34,382 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-07-29 07:37:01,847 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py", line 166, in post
    login(request,user)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 126, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
ERROR 2020-07-29 07:37:36,598 basehttp 154 "POST /login/ HTTP/1.1" 500 90946
INFO 2020-07-29 07:37:57,995 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-07-29 07:40:07,718 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py", line 166, in post
    login(request,user)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 126, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
ERROR 2020-07-29 07:40:07,724 basehttp 154 "POST /login/ HTTP/1.1" 500 90946
INFO 2020-07-29 07:42:14,669 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:42:19,828 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:43:39,948 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 07:43:41,150 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:43:59,351 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 07:44:00,166 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:44:38,210 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 07:44:39,523 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:45:00,935 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 07:45:02,405 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:45:16,358 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 07:45:17,394 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:45:46,948 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:45:57,391 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-07-29 07:45:57,486 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-07-29 07:45:58,857 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-07-29 07:46:01,922 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-07-29 07:46:39,493 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:47:38,652 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 07:47:40,774 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:48:14,811 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 07:48:16,055 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:49:04,916 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-29 07:49:06,125 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:50:20,016 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:50:26,679 basehttp 154 "POST /login/ HTTP/1.1" 200 57
INFO 2020-07-29 07:50:27,588 basehttp 154 "POST /login/ HTTP/1.1" 200 57
INFO 2020-07-29 07:58:54,810 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-29 07:59:01,543 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-07-29 07:59:01,608 basehttp 154 "POST /login/ HTTP/1.1" 200 57
INFO 2020-07-29 07:59:11,512 basehttp 154 "POST /login/ HTTP/1.1" 200 63
INFO 2020-07-29 08:00:43,771 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-07-29 08:00:43,837 basehttp 154 "POST /login/ HTTP/1.1" 200 57
INFO 2020-07-29 08:00:50,976 basehttp 154 "POST /login/ HTTP/1.1" 200 57
INFO 2020-07-30 03:42:30,337 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-30 03:44:36,384 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-30 03:45:19,488 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 03:45:19,489 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-07-30 03:46:26,163 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-07-30 03:46:26,250 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-07-30 03:46:39,922 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-07-30 03:47:52,795 basehttp 154 "GET /image_codes/ba48d95f-5fa6-479a-8f55-3a694b382ce9/ HTTP/1.1" 200 3585
INFO 2020-07-30 03:47:54,721 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-30 03:48:14,042 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-30 03:48:16,869 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-30 03:48:17,683 basehttp 154 "GET /sms_codes/13242327249/?image_code=lsyf&image_code_id=ba48d95f-5fa6-479a-8f55-3a694b382ce9 HTTP/1.1" 200 61
INFO 2020-07-30 03:49:44,140 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
ERROR 2020-07-30 03:49:44,358 log 228 Internal Server Error: /sms_codes/13242327249/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 86, in get
    image_code_server = image_code_server.decode()
AttributeError: 'NoneType' object has no attribute 'decode'
ERROR 2020-07-30 03:49:44,391 basehttp 154 "GET /sms_codes/13242327249/?image_code=lsyf&image_code_id=ba48d95f-5fa6-479a-8f55-3a694b382ce9 HTTP/1.1" 500 82206
INFO 2020-07-30 03:51:05,019 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
ERROR 2020-07-30 03:51:05,287 log 228 Internal Server Error: /sms_codes/13242327249/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 86, in get
    image_code_client = image_code_server.decode()
AttributeError: 'NoneType' object has no attribute 'decode'
ERROR 2020-07-30 03:51:05,367 basehttp 154 "GET /sms_codes/13242327249/?image_code=lsyf&image_code_id=ba48d95f-5fa6-479a-8f55-3a694b382ce9 HTTP/1.1" 500 82206
INFO 2020-07-30 03:51:05,670 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-07-30 03:51:10,854 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-30 03:51:16,915 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
ERROR 2020-07-30 03:51:17,212 log 228 Internal Server Error: /sms_codes/13242327249/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 86, in get
    image_code_client = image_code_server.decode()
AttributeError: 'NoneType' object has no attribute 'decode'
ERROR 2020-07-30 03:51:17,226 basehttp 154 "GET /sms_codes/13242327249/?image_code=lsyf&image_code_id=ba48d95f-5fa6-479a-8f55-3a694b382ce9 HTTP/1.1" 500 82206
INFO 2020-07-30 03:52:26,426 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-30 03:52:34,133 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
ERROR 2020-07-30 03:52:34,377 log 228 Internal Server Error: /sms_codes/13242327249/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 88, in get
    if image_code_client.lower() != image_code_server.decode().lower():
AttributeError: 'NoneType' object has no attribute 'decode'
ERROR 2020-07-30 03:52:34,380 basehttp 154 "GET /sms_codes/13242327249/?image_code=lsyf&image_code_id=ba48d95f-5fa6-479a-8f55-3a694b382ce9 HTTP/1.1" 500 82213
INFO 2020-07-30 03:52:37,870 basehttp 154 "GET /image_codes/de7bedd8-0051-401c-8a61-882fb37db3c6/ HTTP/1.1" 200 3320
INFO 2020-07-30 03:52:43,683 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-30 03:52:44,311 basehttp 154 "GET /sms_codes/13242327249/?image_code=dxse&image_code_id=de7bedd8-0051-401c-8a61-882fb37db3c6 HTTP/1.1" 200 61
INFO 2020-07-30 03:52:59,334 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-30 03:54:07,565 basehttp 154 "GET /image_codes/cf1b0a4d-6c02-4f46-abb1-d598773fb5b9/ HTTP/1.1" 200 3261
INFO 2020-07-30 03:54:15,718 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-30 03:54:16,186 basehttp 154 "GET /sms_codes/13242327249/?image_code=qcVP&image_code_id=cf1b0a4d-6c02-4f46-abb1-d598773fb5b9 HTTP/1.1" 200 61
INFO 2020-07-30 03:57:38,396 basehttp 154 "GET /image_codes/2090fa50-8c14-4e00-b1f3-55b668c88d7e/ HTTP/1.1" 200 3167
INFO 2020-07-30 03:57:44,908 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-30 03:57:44,938 basehttp 154 "GET /sms_codes/13242327249/?image_code=LRKB&image_code_id=2090fa50-8c14-4e00-b1f3-55b668c88d7e HTTP/1.1" 200 61
INFO 2020-07-30 03:58:30,464 basehttp 154 "GET /usernames/lijie/count/ HTTP/1.1" 200 39
INFO 2020-07-30 03:58:30,513 basehttp 154 "GET /mobiles/13242327249/count/ HTTP/1.1" 200 39
INFO 2020-07-30 03:58:30,563 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2020-07-30 03:58:31,050 basehttp 154 "POST /register/ HTTP/1.1" 200 27
WARNING 2020-07-30 03:58:34,482 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 03:58:34,497 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
WARNING 2020-07-30 03:59:20,411 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 03:59:20,412 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-07-30 03:59:33,592 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-07-30 03:59:33,790 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-07-30 03:59:35,164 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 03:59:35,171 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-07-30 04:06:39,347 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-30 04:06:48,171 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-30 10:21:26,590 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-30 10:25:53,166 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 10:25:53,170 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3218
INFO 2020-07-30 10:25:56,396 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-07-30 10:25:56,523 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-07-30 10:26:16,391 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-07-30 10:26:16,676 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-07-30 10:26:18,472 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 10:26:18,475 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3218
WARNING 2020-07-30 10:26:25,763 log 228 Not Found: /info/
WARNING 2020-07-30 10:26:25,770 basehttp 154 "GET /info/ HTTP/1.1" 404 3194
WARNING 2020-07-30 10:26:25,814 log 228 Not Found: /browse_histories/
WARNING 2020-07-30 10:26:25,830 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3230
INFO 2020-07-30 10:26:38,683 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-07-30 10:26:40,726 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 10:26:40,745 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3218
WARNING 2020-07-30 10:26:42,461 log 228 Not Found: /info/
WARNING 2020-07-30 10:26:42,475 basehttp 154 "GET /info/ HTTP/1.1" 404 3194
WARNING 2020-07-30 10:26:42,589 log 228 Not Found: /browse_histories/
WARNING 2020-07-30 10:26:42,589 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3230
INFO 2020-07-30 10:27:11,076 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-07-30 10:27:12,914 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 10:27:12,926 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3218
WARNING 2020-07-30 10:27:15,279 log 228 Not Found: /browse_histories/
WARNING 2020-07-30 10:27:15,294 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3230
WARNING 2020-07-30 10:27:15,293 log 228 Not Found: /info/
WARNING 2020-07-30 10:27:15,295 basehttp 154 "GET /info/ HTTP/1.1" 404 3194
INFO 2020-07-30 10:27:27,960 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-07-30 10:27:29,122 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 10:27:29,128 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3218
WARNING 2020-07-30 10:27:33,680 log 228 Not Found: /info/
WARNING 2020-07-30 10:27:33,710 basehttp 154 "GET /info/ HTTP/1.1" 404 3194
WARNING 2020-07-30 10:27:33,760 log 228 Not Found: /browse_histories/
WARNING 2020-07-30 10:27:33,761 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3230
WARNING 2020-07-30 10:31:13,927 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 10:31:13,937 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3218
WARNING 2020-07-30 10:31:23,688 log 228 Not Found: /info/
WARNING 2020-07-30 10:31:23,717 basehttp 154 "GET /info/ HTTP/1.1" 404 3194
WARNING 2020-07-30 10:31:23,707 log 228 Not Found: /browse_histories/
WARNING 2020-07-30 10:31:23,718 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3230
INFO 2020-07-30 10:31:38,114 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-07-30 10:31:39,959 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 10:31:39,989 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3218
INFO 2020-07-30 10:32:37,348 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-07-30 10:32:40,018 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-30 10:32:45,529 log 228 Not Found: /browse_histories/
WARNING 2020-07-30 10:32:45,588 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3384
ERROR 2020-07-30 10:32:45,795 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/utils/view.py", line 9, in wrapper
    return func(request,*args,**kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py", line 265, in get
    'email_active': user.email_active
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'email_active'
ERROR 2020-07-30 10:32:45,822 basehttp 154 "GET /info/ HTTP/1.1" 500 93379
INFO 2020-07-30 10:32:51,541 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-07-30 10:32:52,935 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 10:32:52,936 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3372
INFO 2020-07-30 11:24:03,215 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-07-30 11:24:03,421 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-07-30 11:25:36,798 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-07-30 11:25:37,000 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-07-30 11:25:37,854 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 11:25:37,855 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3372
WARNING 2020-07-30 11:25:41,550 log 228 Not Found: /browse_histories/
WARNING 2020-07-30 11:25:41,554 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3384
ERROR 2020-07-30 11:25:41,657 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/utils/view.py", line 9, in wrapper
    return func(request,*args,**kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py", line 265, in get
    'email_active': user.email_active
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'email_active'
ERROR 2020-07-30 11:25:41,665 basehttp 154 "GET /info/ HTTP/1.1" 500 93379
INFO 2020-07-30 11:25:51,574 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-07-30 11:25:52,229 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 11:25:52,239 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3372
WARNING 2020-07-30 11:26:00,900 log 228 Not Found: /browse_histories/
WARNING 2020-07-30 11:26:00,921 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3384
ERROR 2020-07-30 11:26:01,015 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/utils/view.py", line 9, in wrapper
    return func(request,*args,**kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py", line 265, in get
    'email_active': user.email_active
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'email_active'
ERROR 2020-07-30 11:26:01,035 basehttp 154 "GET /info/ HTTP/1.1" 500 93379
INFO 2020-07-30 11:26:06,392 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-07-30 11:26:08,551 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 11:26:08,551 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3372
WARNING 2020-07-30 11:26:18,108 log 228 Not Found: /browse_histories/
WARNING 2020-07-30 11:26:18,136 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3384
ERROR 2020-07-30 11:26:18,361 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/utils/view.py", line 9, in wrapper
    return func(request,*args,**kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py", line 265, in get
    'email_active': user.email_active
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'email_active'
ERROR 2020-07-30 11:26:18,388 basehttp 154 "GET /info/ HTTP/1.1" 500 93379
INFO 2020-07-30 11:26:22,062 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-07-30 11:26:23,690 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 11:26:23,701 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3372
WARNING 2020-07-30 11:26:25,483 log 228 Not Found: /browse_histories/
WARNING 2020-07-30 11:26:25,513 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3384
ERROR 2020-07-30 11:26:25,830 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/utils/view.py", line 9, in wrapper
    return func(request,*args,**kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py", line 265, in get
    'email_active': user.email_active
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'email_active'
ERROR 2020-07-30 11:26:25,849 basehttp 154 "GET /info/ HTTP/1.1" 500 93379
INFO 2020-07-30 11:29:49,335 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-30 11:29:51,812 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-30 11:29:53,363 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-07-30 11:29:55,269 log 228 Not Found: /carts/simple/
WARNING 2020-07-30 11:29:55,269 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3372
INFO 2020-07-30 11:29:56,750 basehttp 154 "GET /info/ HTTP/1.1" 200 101
WARNING 2020-07-30 11:29:56,765 log 228 Not Found: /browse_histories/
WARNING 2020-07-30 11:29:56,769 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3384
INFO 2020-07-30 11:57:00,910 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-07-30 11:57:01,967 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-30 11:57:33,155 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-07-30 11:57:34,152 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-30 11:58:28,602 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-07-30 11:58:29,312 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-30 12:25:06,685 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-07-30 12:25:08,581 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-30 12:43:49,212 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/oauth/urls.py changed, reloading.
INFO 2020-07-30 12:43:54,034 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 04:08:55,805 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 04:10:13,806 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-31 04:10:22,947 log 228 Not Found: /carts/simple/
WARNING 2020-07-31 04:10:22,948 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3538
INFO 2020-07-31 04:10:29,143 basehttp 154 "GET /qq/authorization/?next=/ HTTP/1.1" 200 203
WARNING 2020-07-31 04:10:44,418 log 228 Not Found: /oauth_callback/
WARNING 2020-07-31 04:10:44,427 basehttp 154 "GET /oauth_callback/?code=DA7CF6981E26121856474DC8577AF668 HTTP/1.1" 404 3582
WARNING 2020-07-31 04:10:53,302 log 228 Not Found: /oauth_callback/
WARNING 2020-07-31 04:10:53,306 basehttp 154 "GET /oauth_callback/?code=DA7CF6981E26121856474DC8577AF668 HTTP/1.1" 404 3582
INFO 2020-07-31 04:13:01,061 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/oauth/views.py changed, reloading.
INFO 2020-07-31 04:13:02,606 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 04:17:02,568 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/oauth/views.py changed, reloading.
INFO 2020-07-31 04:17:04,465 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 04:17:32,861 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/oauth/views.py changed, reloading.
INFO 2020-07-31 04:17:34,275 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 04:17:44,000 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/oauth/views.py changed, reloading.
INFO 2020-07-31 04:17:45,113 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 04:17:59,600 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/oauth/views.py changed, reloading.
INFO 2020-07-31 04:18:00,995 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 04:18:22,696 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/oauth/views.py changed, reloading.
INFO 2020-07-31 04:18:24,961 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 04:18:57,482 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/oauth/views.py changed, reloading.
INFO 2020-07-31 04:18:59,214 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-31 04:19:17,463 log 228 Not Found: /oauth_callback/
WARNING 2020-07-31 04:19:17,464 basehttp 154 "GET /oauth_callback/?code=79DBE06F8BE695630C479A0880E78550 HTTP/1.1" 404 3582
INFO 2020-07-31 04:22:06,730 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-07-31 04:22:09,864 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-07-31 04:22:18,501 log 228 Internal Server Error: /oauth_callback/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'meiduo_mall_db.tb_oauth_qq' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/oauth/views.py", line 97, in get
    oauth_qq = OAuthQQUser.objects.get(openid=openid)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'meiduo_mall_db.tb_oauth_qq' doesn't exist")
ERROR 2020-07-31 04:22:18,517 basehttp 154 "GET /oauth_callback/?code=79DBE06F8BE695630C479A0880E78550 HTTP/1.1" 500 217472
INFO 2020-07-31 04:24:01,867 basehttp 154 "GET /oauth_callback/?code=79DBE06F8BE695630C479A0880E78550 HTTP/1.1" 200 59
ERROR 2020-07-31 04:24:02,069 log 228 Internal Server Error: /image_codes/8115c2ff-56a1-414c-8d9d-b387d99cc538/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 26, in get
    text,image =Captcha.generate_captcha()
TypeError: generate_captcha() missing 1 required positional argument: 'self'
ERROR 2020-07-31 04:24:02,091 basehttp 154 "GET /image_codes/8115c2ff-56a1-414c-8d9d-b387d99cc538/ HTTP/1.1" 500 81336
INFO 2020-07-31 04:28:35,884 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 04:28:39,384 basehttp 154 "GET /oauth_callback/?code=79DBE06F8BE695630C479A0880E78550 HTTP/1.1" 200 59
INFO 2020-07-31 04:28:39,636 basehttp 154 "GET /image_codes/3f07de69-02b9-4cf5-a368-c05729edbae7/ HTTP/1.1" 200 3470
INFO 2020-07-31 04:30:57,668 basehttp 154 "GET /sms_codes/13242327249/?image_code=rpab&image_code_id=3f07de69-02b9-4cf5-a368-c05729edbae7 HTTP/1.1" 200 61
INFO 2020-07-31 04:31:40,450 basehttp 154 "OPTIONS /oauth_callback/ HTTP/1.1" 200 0
INFO 2020-07-31 04:31:40,465 basehttp 154 "POST /oauth_callback/ HTTP/1.1" 200 51
WARNING 2020-07-31 04:31:42,401 log 228 Not Found: /carts/simple/
WARNING 2020-07-31 04:31:42,405 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-07-31 04:31:45,765 basehttp 154 "GET /info/ HTTP/1.1" 200 63
WARNING 2020-07-31 04:31:45,811 log 228 Not Found: /browse_histories/
WARNING 2020-07-31 04:31:45,812 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
INFO 2020-07-31 04:31:58,457 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-07-31 04:31:58,468 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-07-31 04:32:02,549 basehttp 154 "GET /qq/authorization/?next=/ HTTP/1.1" 200 203
INFO 2020-07-31 04:32:23,994 basehttp 154 "GET /oauth_callback/?code=811C71ECAB97A5515829AA2DE601C4E0 HTTP/1.1" 200 234
INFO 2020-07-31 04:32:24,052 basehttp 154 "GET /image_codes/d74bdf6c-5ea7-4f3e-a33f-727401f167ec/ HTTP/1.1" 200 3376
WARNING 2020-07-31 04:33:29,554 log 228 Not Found: /carts/simple/
WARNING 2020-07-31 04:33:29,569 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-07-31 04:33:34,363 basehttp 154 "GET /qq/authorization/?next=/ HTTP/1.1" 200 203
INFO 2020-07-31 04:34:24,690 basehttp 154 "GET /oauth_callback/?code=175F7ADCEE5F8872BA59A5F330F4233F HTTP/1.1" 200 234
INFO 2020-07-31 04:34:24,733 basehttp 154 "GET /image_codes/18dd2067-e48f-47f8-8553-a283d651aad5/ HTTP/1.1" 200 3550
ERROR 2020-07-31 06:23:56,819 log 228 Internal Server Error: /sms_codes/13242327249/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 88, in get
    if image_code_client.lower() != image_code_server.decode().lower():
AttributeError: 'NoneType' object has no attribute 'decode'
ERROR 2020-07-31 06:23:56,831 basehttp 154 "GET /sms_codes/13242327249/?image_code=LWZD&image_code_id=18dd2067-e48f-47f8-8553-a283d651aad5 HTTP/1.1" 500 82749
INFO 2020-07-31 06:27:30,617 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 06:27:36,381 basehttp 154 "GET /oauth_callback/?code=175F7ADCEE5F8872BA59A5F330F4233F HTTP/1.1" 200 59
INFO 2020-07-31 06:27:36,476 basehttp 154 "GET /image_codes/989b03b9-c6a2-4a09-aece-9ba674f913b4/ HTTP/1.1" 200 3305
INFO 2020-07-31 06:28:21,584 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-07-31 06:28:23,069 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 06:30:37,134 basehttp 154 "GET /oauth_callback/?code=175F7ADCEE5F8872BA59A5F330F4233F HTTP/1.1" 200 59
ERROR 2020-07-31 06:30:37,447 log 228 Internal Server Error: /image_codes/11113b7d-0969-4391-a2ec-fc8eb40e1cce/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 26, in get
    text,image =captcha.generate_captcha('django')
TypeError: generate_captcha() takes 1 positional argument but 2 were given
ERROR 2020-07-31 06:30:37,448 basehttp 154 "GET /image_codes/11113b7d-0969-4391-a2ec-fc8eb40e1cce/ HTTP/1.1" 500 80892
ERROR 2020-07-31 06:30:41,043 log 228 Internal Server Error: /image_codes/f4577f88-2b4d-4c0b-ae24-ee16fe8341e6/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 26, in get
    text,image =captcha.generate_captcha('django')
TypeError: generate_captcha() takes 1 positional argument but 2 were given
ERROR 2020-07-31 06:30:41,044 basehttp 154 "GET /image_codes/f4577f88-2b4d-4c0b-ae24-ee16fe8341e6/ HTTP/1.1" 500 80892
INFO 2020-07-31 06:31:43,727 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-07-31 06:31:44,724 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 06:32:36,224 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-07-31 06:32:39,190 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 06:32:48,350 basehttp 154 "GET /oauth_callback/?code=0148AB463CB5268BACFF7FC350C374F1 HTTP/1.1" 200 234
INFO 2020-07-31 06:32:48,531 basehttp 154 "GET /image_codes/31344428-ebe1-47d2-9d2c-76301f0133c4/ HTTP/1.1" 200 3121
INFO 2020-07-31 06:32:56,302 views 96 371182
INFO 2020-07-31 06:32:56,582 basehttp 154 "GET /sms_codes/13242327249/?image_code=j85n&image_code_id=31344428-ebe1-47d2-9d2c-76301f0133c4 HTTP/1.1" 200 61
INFO 2020-07-31 06:33:08,403 basehttp 154 "OPTIONS /oauth_callback/ HTTP/1.1" 200 0
ERROR 2020-07-31 06:33:08,501 log 228 Internal Server Error: /oauth_callback/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/oauth/views.py", line 138, in post
    conn = get_redis_connection('sms_code')
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django_redis/__init__.py", line 12, in get_redis_connection
    cache = caches[alias]
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/cache/__init__.py", line 76, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'sms_code' in settings.CACHES
ERROR 2020-07-31 06:33:08,520 basehttp 154 "POST /oauth_callback/ HTTP/1.1" 500 89856
INFO 2020-07-31 06:47:35,920 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 06:47:43,545 basehttp 154 "GET /image_codes/39b1edd6-9f59-43df-9866-06c0cdfe9065/ HTTP/1.1" 200 2935
INFO 2020-07-31 06:47:53,770 basehttp 154 "GET /sms_codes/13242327249/?image_code=7qps&image_code_id=39b1edd6-9f59-43df-9866-06c0cdfe9065 HTTP/1.1" 200 75
ERROR 2020-07-31 06:49:01,811 log 228 Internal Server Error: /sms_codes/13242327249/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 88, in get
    if image_code_client.lower() != image_code_server.decode().lower():
AttributeError: 'NoneType' object has no attribute 'decode'
ERROR 2020-07-31 06:49:01,817 basehttp 154 "GET /sms_codes/13242327249/?image_code=7qps&image_code_id=39b1edd6-9f59-43df-9866-06c0cdfe9065 HTTP/1.1" 500 82749
ERROR 2020-07-31 06:49:16,341 log 228 Internal Server Error: /sms_codes/13242327249/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 88, in get
    if image_code_client.lower() != image_code_server.decode().lower():
AttributeError: 'NoneType' object has no attribute 'decode'
ERROR 2020-07-31 06:49:16,343 basehttp 154 "GET /sms_codes/13242327249/?image_code=7qps&image_code_id=39b1edd6-9f59-43df-9866-06c0cdfe9065 HTTP/1.1" 500 82749
INFO 2020-07-31 07:38:08,232 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-07-31 07:38:09,645 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 07:40:02,549 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-07-31 07:40:03,746 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 07:40:12,258 basehttp 154 "GET /image_codes/85a31419-4e5c-4307-8fc1-d3a44cdd9b22/ HTTP/1.1" 200 3157
ERROR 2020-07-31 07:40:18,636 log 228 Internal Server Error: /sms_codes/13242327249/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 85, in get
    conn = get_redis_connection('sms_code')
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django_redis/__init__.py", line 12, in get_redis_connection
    cache = caches[alias]
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/cache/__init__.py", line 76, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'sms_code' in settings.CACHES
ERROR 2020-07-31 07:40:18,648 basehttp 154 "GET /sms_codes/13242327249/?image_code=mbqp&image_code_id=85a31419-4e5c-4307-8fc1-d3a44cdd9b22 HTTP/1.1" 500 90755
WARNING 2020-07-31 07:40:27,045 log 228 Bad Request: /sms_codes/13242327249/
WARNING 2020-07-31 07:40:27,045 basehttp 154 "GET /sms_codes/13242327249/?image_code=mbqp&image_code_id=85a31419-4e5c-4307-8fc1-d3a44cdd9b22 HTTP/1.1" 400 57
INFO 2020-07-31 09:44:48,150 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-31 09:44:53,184 log 228 Bad Request: /sms_codes/13242327249/
WARNING 2020-07-31 09:44:53,185 basehttp 154 "GET /sms_codes/13242327249/?image_code=mbqp&image_code_id=85a31419-4e5c-4307-8fc1-d3a44cdd9b22 HTTP/1.1" 400 57
INFO 2020-07-31 09:49:48,837 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 09:49:53,125 basehttp 154 "GET /image_codes/97ec80ad-4f60-4380-b96f-46e34b792213/ HTTP/1.1" 200 3053
INFO 2020-07-31 09:49:54,390 basehttp 154 "GET /image_codes/26a7c27c-d1a5-404f-ae36-7edf064e70cc/ HTTP/1.1" 200 3364
ERROR 2020-07-31 09:50:01,195 log 228 Internal Server Error: /sms_codes/13242327249/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 85, in get
    conn = get_redis_connection('sms_code')
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django_redis/__init__.py", line 12, in get_redis_connection
    cache = caches[alias]
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/cache/__init__.py", line 76, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'sms_code' in settings.CACHES
ERROR 2020-07-31 09:50:01,201 basehttp 154 "GET /sms_codes/13242327249/?image_code=rznc&image_code_id=26a7c27c-d1a5-404f-ae36-7edf064e70cc HTTP/1.1" 500 90755
INFO 2020-07-31 09:52:19,695 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-07-31 09:52:20,884 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-31 09:52:22,933 log 228 Bad Request: /sms_codes/13242327249/
WARNING 2020-07-31 09:52:22,935 basehttp 154 "GET /sms_codes/13242327249/?image_code=rznc&image_code_id=26a7c27c-d1a5-404f-ae36-7edf064e70cc HTTP/1.1" 400 57
INFO 2020-07-31 09:52:32,765 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 09:52:41,710 basehttp 154 "GET /image_codes/6d78bb18-c007-4326-84ff-1bfce675bb9f/ HTTP/1.1" 200 3275
INFO 2020-07-31 09:52:44,371 basehttp 154 "GET /image_codes/0fc2a4e6-094a-4d55-85a9-dc571152e611/ HTTP/1.1" 200 2921
ERROR 2020-07-31 09:53:10,181 log 228 Internal Server Error: /sms_codes/13242327249/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 87, in get
    flag = conn.get('flag_%s'%mobile)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 192.168.203.151:6379. Connection refused.
ERROR 2020-07-31 09:53:10,183 basehttp 154 "GET /sms_codes/13242327249/?image_code=xjff&image_code_id=0fc2a4e6-094a-4d55-85a9-dc571152e611 HTTP/1.1" 500 114382
INFO 2020-07-31 09:53:43,740 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-31 09:53:49,874 log 228 Bad Request: /sms_codes/13242327249/
WARNING 2020-07-31 09:53:49,877 basehttp 154 "GET /sms_codes/13242327249/?image_code=xjff&image_code_id=0fc2a4e6-094a-4d55-85a9-dc571152e611 HTTP/1.1" 400 57
INFO 2020-07-31 09:53:57,880 basehttp 154 "GET /image_codes/bdfc209c-bbf9-425e-ab94-7df39615dfec/ HTTP/1.1" 200 3170
INFO 2020-07-31 09:54:03,920 basehttp 154 "GET /image_codes/321c0610-4914-410f-8ed3-0bd84c522593/ HTTP/1.1" 200 3272
INFO 2020-07-31 09:54:06,368 basehttp 154 "GET /image_codes/6cf698e2-d574-492a-8778-e455eab65506/ HTTP/1.1" 200 3342
INFO 2020-07-31 09:54:15,754 views 92 693945
INFO 2020-07-31 09:54:15,955 basehttp 154 "GET /sms_codes/13242327249/?image_code=equg&image_code_id=6cf698e2-d574-492a-8778-e455eab65506 HTTP/1.1" 200 61
INFO 2020-07-31 09:54:27,382 basehttp 154 "OPTIONS /oauth_callback/ HTTP/1.1" 200 0
INFO 2020-07-31 09:54:27,479 basehttp 154 "POST /oauth_callback/ HTTP/1.1" 200 27
WARNING 2020-07-31 09:54:28,411 log 228 Not Found: /carts/simple/
WARNING 2020-07-31 09:54:28,414 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-07-31 09:55:25,200 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-07-31 09:55:25,222 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-07-31 09:55:28,592 basehttp 154 "GET /qq/authorization/?next=/ HTTP/1.1" 200 203
INFO 2020-07-31 09:55:36,540 basehttp 154 "GET /oauth_callback/?code=ACFA97D2F0445E66BB52BA7345F7CF96 HTTP/1.1" 200 27
WARNING 2020-07-31 09:55:37,057 log 228 Not Found: /carts/simple/
WARNING 2020-07-31 09:55:37,059 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-07-31 10:00:13,696 log 228 Not Found: /browse_histories/
WARNING 2020-07-31 10:00:13,723 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
INFO 2020-07-31 10:00:13,981 basehttp 154 "GET /info/ HTTP/1.1" 200 124
INFO 2020-07-31 10:02:59,640 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-07-31 10:03:00,942 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 10:11:18,835 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-31 10:11:19,845 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 10:11:46,395 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-31 10:11:47,121 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 10:12:22,462 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
ERROR 2020-07-31 10:12:22,582 log 228 Internal Server Error: /emails/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/utils/view.py", line 9, in wrapper
    return func(request,*args,**kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py", line 277, in put
    email = json_dict('email')
TypeError: 'dict' object is not callable
ERROR 2020-07-31 10:12:22,583 basehttp 154 "PUT /emails/ HTTP/1.1" 500 90104
ERROR 2020-07-31 10:12:40,215 log 228 Internal Server Error: /emails/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/utils/view.py", line 9, in wrapper
    return func(request,*args,**kwargs)
  File "/home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py", line 277, in put
    email = json_dict('email')
TypeError: 'dict' object is not callable
ERROR 2020-07-31 10:12:40,217 basehttp 154 "PUT /emails/ HTTP/1.1" 500 90104
INFO 2020-07-31 10:13:16,570 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-07-31 10:13:17,429 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 10:13:22,836 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-07-31 11:35:53,336 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-07-31 11:35:54,894 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-07-31 11:36:01,642 log 228 Not Found: /browse_histories/
WARNING 2020-07-31 11:36:01,643 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3870
INFO 2020-07-31 11:36:01,712 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-07-31 11:36:12,575 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-07-31 11:36:12,666 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
WARNING 2020-07-31 11:36:25,558 log 228 Not Found: /carts/simple/
WARNING 2020-07-31 11:36:25,559 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3858
WARNING 2020-07-31 11:36:38,702 log 228 Not Found: /carts/simple/
WARNING 2020-07-31 11:36:38,702 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3858
INFO 2020-07-31 11:48:17,176 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-07-31 11:48:21,940 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 12:44:24,171 autoreload 597 Watching for file changes with StatReloader
INFO 2020-07-31 12:44:35,879 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-07-31 12:44:36,135 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-07-31 12:44:36,792 log 228 Not Found: /carts/simple/
WARNING 2020-07-31 12:44:36,793 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3858
INFO 2020-07-31 12:47:46,676 basehttp 154 "GET /info/ HTTP/1.1" 200 141
WARNING 2020-07-31 12:47:46,715 log 228 Not Found: /browse_histories/
WARNING 2020-07-31 12:47:46,720 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3870
INFO 2020-08-01 03:00:14,365 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 03:00:29,429 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-08-01 03:00:29,702 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-08-01 03:00:30,561 log 228 Not Found: /carts/simple/
WARNING 2020-08-01 03:00:30,561 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 4027
WARNING 2020-08-01 03:00:35,019 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 03:00:35,024 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-08-01 03:00:35,025 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-08-01 03:04:18,057 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2020-08-01 03:04:18,287 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-08-01 03:08:50,907 autoreload 217 /home/ubuntu/meiduo_mall/celery_tasks/email/tasks.py changed, reloading.
INFO 2020-08-01 03:08:51,573 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-01 03:08:54,004 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 03:08:54,005 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-08-01 03:08:54,035 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-08-01 03:08:55,818 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-08-01 03:09:24,318 basehttp 154 "OPTIONS /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU5NjI1MTMzNSwiZXhwIjoxNTk2MzM3NzM1fQ.eyJ1c2VyX2lkIjo4LCJlbWF HTTP/1.1" 200 0
INFO 2020-08-01 03:09:24,393 basehttp 154 "PUT /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU5NjI1MTMzNSwiZXhwIjoxNTk2MzM3NzM1fQ.eyJ1c2VyX2lkIjo4LCJlbWF HTTP/1.1" 200 50
WARNING 2020-08-01 03:09:35,740 log 228 Not Found: /carts/simple/
WARNING 2020-08-01 03:09:35,742 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 4027
WARNING 2020-08-01 03:09:38,202 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 03:09:38,203 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-08-01 03:09:38,230 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-08-01 03:13:00,455 autoreload 217 /home/ubuntu/meiduo_mall/celery_tasks/email/tasks.py changed, reloading.
INFO 2020-08-01 03:13:01,599 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 03:13:03,322 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 03:13:07,455 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2020-08-01 03:13:07,628 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-08-01 03:14:06,562 autoreload 217 /home/ubuntu/meiduo_mall/celery_tasks/email/tasks.py changed, reloading.
INFO 2020-08-01 03:14:07,164 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 03:14:24,753 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 03:16:48,858 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 03:20:26,204 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-08-01 03:20:26,329 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-08-01 03:20:26,926 log 228 Not Found: /carts/simple/
WARNING 2020-08-01 03:20:26,927 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 4027
INFO 2020-08-01 03:20:29,289 basehttp 154 "GET /info/ HTTP/1.1" 200 141
WARNING 2020-08-01 03:20:29,311 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 03:20:29,317 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-08-01 03:20:31,075 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-08-01 03:21:01,772 basehttp 154 "OPTIONS /emails/verification/ HTTP/1.1" 200 0
INFO 2020-08-01 03:21:01,784 basehttp 154 "PUT /emails/verification/ HTTP/1.1" 200 56
INFO 2020-08-01 03:21:03,053 basehttp 154 "OPTIONS /emails/verification/ HTTP/1.1" 200 0
INFO 2020-08-01 03:21:03,162 basehttp 154 "PUT /emails/verification/ HTTP/1.1" 200 56
INFO 2020-08-01 03:21:03,170 basehttp 154 "OPTIONS /emails/verification/ HTTP/1.1" 200 0
INFO 2020-08-01 03:21:03,296 basehttp 154 "PUT /emails/verification/ HTTP/1.1" 200 56
INFO 2020-08-01 03:40:15,836 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-08-01 03:40:16,741 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-01 03:40:19,810 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 03:40:19,823 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-08-01 03:40:19,853 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-08-01 03:40:20,971 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2020-08-01 03:40:21,252 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-08-01 03:45:01,990 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-08-01 03:45:03,567 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 03:45:24,685 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-08-01 03:45:24,822 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-08-01 03:45:25,337 log 228 Not Found: /carts/simple/
WARNING 2020-08-01 03:45:25,338 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 4027
INFO 2020-08-01 03:45:27,486 basehttp 154 "GET /info/ HTTP/1.1" 200 141
WARNING 2020-08-01 03:45:27,510 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 03:45:27,510 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-08-01 03:45:32,291 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-08-01 03:47:59,536 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-08-01 03:48:00,130 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-01 03:48:02,193 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 03:48:02,202 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-08-01 03:48:02,231 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-08-01 03:48:03,289 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2020-08-01 03:48:56,761 log 228 Not Found: /browse_histories/
INFO 2020-08-01 03:48:56,762 basehttp 154 "GET /info/ HTTP/1.1" 200 141
WARNING 2020-08-01 03:48:56,776 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-08-01 03:48:58,642 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-08-01 03:49:17,010 basehttp 154 "GET /info/ HTTP/1.1" 200 141
WARNING 2020-08-01 03:49:17,014 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 03:49:17,037 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-08-01 03:49:18,576 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-08-01 03:52:16,879 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-08-01 03:52:17,475 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 03:54:16,677 autoreload 217 /home/ubuntu/meiduo_mall/celery_tasks/main.py changed, reloading.
INFO 2020-08-01 03:54:17,400 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-01 03:54:19,066 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 03:54:19,067 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-08-01 03:54:19,121 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-08-01 03:54:20,636 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2020-08-01 03:54:20,832 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-08-01 04:40:42,978 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-01 04:40:47,883 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 04:40:47,886 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 77
INFO 2020-08-01 04:40:47,917 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-08-01 04:40:49,510 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2020-08-01 04:40:49,708 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-08-01 04:49:19,186 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2020-08-01 04:49:20,656 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-01 04:49:23,886 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 04:49:23,889 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 77
INFO 2020-08-01 04:49:23,950 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-08-01 04:49:25,494 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2020-08-01 04:50:30,181 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 04:50:30,181 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 77
INFO 2020-08-01 04:50:30,188 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-08-01 04:50:38,073 basehttp 154 "GET /info/ HTTP/1.1" 200 63
WARNING 2020-08-01 04:50:38,078 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 04:50:38,078 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 77
INFO 2020-08-01 04:50:40,649 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-08-01 04:50:40,771 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-08-01 04:50:41,305 log 228 Not Found: /carts/simple/
WARNING 2020-08-01 04:50:41,307 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 77
WARNING 2020-08-01 04:50:44,424 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 04:50:44,428 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 77
INFO 2020-08-01 04:50:44,432 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-08-01 04:50:45,748 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2020-08-01 04:50:45,808 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2020-08-01 04:54:42,845 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 04:54:42,847 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 77
INFO 2020-08-01 04:54:42,882 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-08-01 04:54:51,049 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2020-08-01 04:56:01,372 log 228 Not Found: /browse_histories/
INFO 2020-08-01 04:56:01,381 basehttp 154 "GET /info/ HTTP/1.1" 200 141
WARNING 2020-08-01 04:56:01,390 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 77
INFO 2020-08-01 04:59:41,206 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-08-01 04:59:42,476 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 05:00:02,320 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 05:00:09,893 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-08-01 05:04:44,160 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/urls.py changed, reloading.
INFO 2020-08-01 05:04:46,854 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 05:07:57,921 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/areas/urls.py changed, reloading.
INFO 2020-08-01 05:07:58,808 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 05:10:12,070 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/areas/urls.py changed, reloading.
INFO 2020-08-01 05:10:12,559 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 07:43:48,674 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 07:51:34,961 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 07:54:13,429 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 07:56:51,116 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 08:00:56,035 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 08:08:02,056 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 08:11:53,521 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 08:14:13,351 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 08:14:43,328 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-08-01 08:14:47,052 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-01 08:16:28,961 log 228 Not Found: /addresses/
ERROR 2020-08-01 08:16:28,961 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
WARNING 2020-08-01 08:16:28,964 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
ERROR 2020-08-01 08:16:28,973 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
INFO 2020-08-01 08:18:35,418 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/areas/views.py changed, reloading.
INFO 2020-08-01 08:18:36,157 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-01 08:21:39,171 log 228 Not Found: /browse_histories/
WARNING 2020-08-01 08:21:39,172 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 77
INFO 2020-08-01 08:21:39,202 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-08-01 08:21:40,612 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2020-08-01 08:21:40,775 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-08-01 08:22:06,939 basehttp 154 "OPTIONS /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU5NjI3MDEwMCwiZXhwIjoxNTk2MzU2NTAwfQ.eyJ1c2VyX2lkIjo4LCJlbWFpbCI6IjIzODYyMzQyODJAcXEuY29tIn0._bgJCAif4IvpYJcmPjOSAgMyIKtMqhVEDdfUioQLY2kaThU_M546tLUgey_BmZqMVpbr1E1Fa0lfkth4UfaHUg HTTP/1.1" 200 0
INFO 2020-08-01 08:22:06,995 basehttp 154 "PUT /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU5NjI3MDEwMCwiZXhwIjoxNTk2MzU2NTAwfQ.eyJ1c2VyX2lkIjo4LCJlbWFpbCI6IjIzODYyMzQyODJAcXEuY29tIn0._bgJCAif4IvpYJcmPjOSAgMyIKtMqhVEDdfUioQLY2kaThU_M546tLUgey_BmZqMVpbr1E1Fa0lfkth4UfaHUg HTTP/1.1" 200 67
WARNING 2020-08-01 08:22:09,344 log 228 Not Found: /carts/simple/
WARNING 2020-08-01 08:22:09,344 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 77
INFO 2020-08-01 08:34:39,345 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/areas/urls.py changed, reloading.
INFO 2020-08-01 08:34:40,211 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 08:35:26,344 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/areas/views.py changed, reloading.
INFO 2020-08-01 08:35:27,402 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-08-01 08:57:47,079 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
WARNING 2020-08-01 08:57:47,083 log 228 Not Found: /addresses/
ERROR 2020-08-01 08:57:47,087 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
WARNING 2020-08-01 08:57:47,091 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
INFO 2020-08-01 08:59:55,625 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2020-08-01 08:59:56,494 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 09:00:32,128 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2020-08-01 09:00:32,627 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 09:01:14,482 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2020-08-01 09:01:15,008 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 09:02:39,557 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2020-08-01 09:02:40,114 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 09:21:28,560 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-08-01 09:21:31,110 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 09:21:40,929 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-08-01 09:21:42,242 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 09:21:50,852 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 09:22:22,822 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-01 09:22:39,478 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-08-01 09:27:27,122 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
WARNING 2020-08-01 09:27:27,127 log 228 Not Found: /addresses/
ERROR 2020-08-01 09:27:27,138 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
WARNING 2020-08-01 09:27:27,139 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
WARNING 2020-08-01 09:28:20,847 log 228 Not Found: /addresses/
WARNING 2020-08-01 09:28:20,849 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
ERROR 2020-08-01 09:28:20,854 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR 2020-08-01 09:28:20,855 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
INFO 2020-08-01 09:28:58,556 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-08-01 09:29:03,540 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR 2020-08-01 09:29:03,550 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
WARNING 2020-08-01 09:29:03,545 log 228 Not Found: /addresses/
WARNING 2020-08-01 09:29:03,554 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
INFO 2020-08-01 09:31:21,676 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-08-01 09:31:29,961 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR 2020-08-01 09:31:29,970 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
WARNING 2020-08-01 09:31:29,963 log 228 Not Found: /addresses/
WARNING 2020-08-01 09:31:29,974 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
INFO 2020-08-02 01:23:29,442 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-02 01:23:36,383 log 228 Not Found: /carts/simple/
WARNING 2020-08-02 01:23:36,383 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 77
WARNING 2020-08-02 01:23:42,836 log 228 Not Found: /browse_histories/
WARNING 2020-08-02 01:23:42,872 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 77
INFO 2020-08-02 01:23:42,863 basehttp 154 "GET /info/ HTTP/1.1" 200 140
WARNING 2020-08-02 01:23:44,891 log 228 Not Found: /addresses/
WARNING 2020-08-02 01:23:44,892 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
ERROR 2020-08-02 01:23:44,896 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR 2020-08-02 01:23:44,899 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
WARNING 2020-08-02 01:24:56,811 log 228 Not Found: /addresses/
WARNING 2020-08-02 01:24:56,812 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
ERROR 2020-08-02 01:24:56,814 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR 2020-08-02 01:24:56,815 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
INFO 2020-08-02 01:25:46,810 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-02 01:25:51,175 log 228 Not Found: /addresses/
ERROR 2020-08-02 01:25:51,177 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR 2020-08-02 01:25:51,185 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
WARNING 2020-08-02 01:25:51,184 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
INFO 2020-08-02 01:27:21,857 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-08-02 01:27:38,022 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR 2020-08-02 01:27:38,028 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
WARNING 2020-08-02 01:27:38,039 log 228 Not Found: /addresses/
WARNING 2020-08-02 01:27:38,046 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
INFO 2020-08-02 02:18:19,883 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-08-02 02:18:22,564 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 02:28:57,733 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/areas/views.py changed, reloading.
INFO 2020-08-02 02:28:59,138 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-02 02:29:00,741 log 228 Not Found: /addresses/
ERROR 2020-08-02 02:29:00,742 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
WARNING 2020-08-02 02:29:00,748 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
ERROR 2020-08-02 02:29:00,756 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
WARNING 2020-08-02 02:33:29,293 log 228 Not Found: /addresses/
ERROR 2020-08-02 02:33:29,301 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR 2020-08-02 02:33:29,309 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
WARNING 2020-08-02 02:33:29,307 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
INFO 2020-08-02 02:33:29,336 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/areas/views.py changed, reloading.
INFO 2020-08-02 02:33:31,198 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 02:34:05,748 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-08-02 02:34:09,655 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR 2020-08-02 02:34:09,667 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
WARNING 2020-08-02 02:34:09,661 log 228 Not Found: /addresses/
WARNING 2020-08-02 02:34:09,684 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
ERROR 2020-08-02 02:34:32,339 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR 2020-08-02 02:34:32,344 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
WARNING 2020-08-02 02:34:32,341 log 228 Not Found: /addresses/
WARNING 2020-08-02 02:34:32,346 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
WARNING 2020-08-02 02:36:19,190 log 228 Not Found: /addresses/
WARNING 2020-08-02 02:36:19,197 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
ERROR 2020-08-02 02:36:19,221 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR 2020-08-02 02:36:19,235 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
WARNING 2020-08-02 02:36:35,156 log 228 Not Found: /addresses/
WARNING 2020-08-02 02:36:35,158 basehttp 154 "GET /addresses/ HTTP/1.1" 404 77
ERROR 2020-08-02 02:36:35,178 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR 2020-08-02 02:36:35,186 basehttp 154 "GET /areas/ HTTP/1.1" 500 27
INFO 2020-08-02 02:37:59,965 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-02 02:38:02,973 log 228 Not Found: /addresses/
WARNING 2020-08-02 02:38:03,004 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
ERROR 2020-08-02 02:38:03,186 log 228 Internal Server Error: /areas/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_38/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR 2020-08-02 02:38:03,190 basehttp 154 "GET /areas/ HTTP/1.1" 500 79105
INFO 2020-08-02 02:38:42,692 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/areas/views.py changed, reloading.
INFO 2020-08-02 02:38:43,901 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-02 02:38:46,916 log 228 Not Found: /addresses/
WARNING 2020-08-02 02:38:46,922 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
INFO 2020-08-02 02:38:46,968 basehttp 154 "GET /areas/ HTTP/1.1" 200 1767
INFO 2020-08-02 02:39:08,757 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/areas/views.py changed, reloading.
INFO 2020-08-02 02:39:10,057 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-08-02 02:39:12,726 log 228 Not Found: /addresses/
WARNING 2020-08-02 02:39:12,742 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
INFO 2020-08-02 02:39:12,785 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 03:06:37,507 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-08-02 03:06:38,791 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 03:52:48,349 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-08-02 03:52:52,812 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 03:52:58,852 basehttp 154 "GET /areas/440000/ HTTP/1.1" 200 1061
INFO 2020-08-02 03:53:03,777 basehttp 154 "GET /areas/440300/ HTTP/1.1" 200 371
INFO 2020-08-02 03:53:26,370 basehttp 154 "OPTIONS /addresses/create/ HTTP/1.1" 200 0
INFO 2020-08-02 03:53:26,513 basehttp 154 "POST /addresses/create/ HTTP/1.1" 200 288
INFO 2020-08-02 03:53:26,992 basehttp 154 "GET /addresses/ HTTP/1.1" 200 283
INFO 2020-08-02 03:53:27,037 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 03:53:36,289 basehttp 154 "GET /areas/130000/ HTTP/1.1" 200 701
INFO 2020-08-02 03:53:37,224 basehttp 154 "GET /areas/130300/ HTTP/1.1" 200 459
INFO 2020-08-02 03:53:56,355 basehttp 154 "POST /addresses/create/ HTTP/1.1" 200 297
INFO 2020-08-02 03:53:56,746 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 03:53:56,771 basehttp 154 "GET /addresses/ HTTP/1.1" 200 508
INFO 2020-08-02 03:55:06,747 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-08-02 03:55:08,338 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 03:55:46,730 basehttp 154 "OPTIONS /addresses/2/default/ HTTP/1.1" 200 0
WARNING 2020-08-02 03:55:46,766 log 228 Not Found: /addresses/2/default/
WARNING 2020-08-02 03:55:46,767 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 4706
WARNING 2020-08-02 03:55:48,120 log 228 Not Found: /addresses/2/default/
WARNING 2020-08-02 03:55:48,121 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 4706
WARNING 2020-08-02 03:55:48,657 log 228 Not Found: /addresses/2/default/
WARNING 2020-08-02 03:55:48,657 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 4706
WARNING 2020-08-02 03:55:48,840 log 228 Not Found: /addresses/2/default/
WARNING 2020-08-02 03:55:48,841 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 4706
WARNING 2020-08-02 03:55:49,034 log 228 Not Found: /addresses/2/default/
WARNING 2020-08-02 03:55:49,034 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 4706
WARNING 2020-08-02 03:55:49,217 log 228 Not Found: /addresses/2/default/
WARNING 2020-08-02 03:55:49,221 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 4706
WARNING 2020-08-02 03:55:49,404 log 228 Not Found: /addresses/2/default/
WARNING 2020-08-02 03:55:49,405 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 4706
WARNING 2020-08-02 03:55:49,585 log 228 Not Found: /addresses/2/default/
WARNING 2020-08-02 03:55:49,588 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 4706
INFO 2020-08-02 04:10:57,937 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-08-02 04:11:01,672 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 04:21:28,163 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-08-02 04:21:30,924 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 04:21:35,491 basehttp 154 "OPTIONS /addresses/2/default/ HTTP/1.1" 200 0
WARNING 2020-08-02 04:21:35,535 log 228 Not Found: /addresses/2/default/
WARNING 2020-08-02 04:21:35,537 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 5076
INFO 2020-08-02 04:21:38,675 basehttp 154 "OPTIONS /addresses/2/ HTTP/1.1" 200 0
INFO 2020-08-02 04:21:38,703 basehttp 154 "DELETE /addresses/2/ HTTP/1.1" 200 61
INFO 2020-08-02 04:21:39,318 basehttp 154 "GET /addresses/ HTTP/1.1" 200 283
INFO 2020-08-02 04:21:39,342 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 04:21:44,474 basehttp 154 "GET /areas/140000/ HTTP/1.1" 200 601
INFO 2020-08-02 04:21:45,501 basehttp 154 "GET /areas/140400/ HTTP/1.1" 200 675
INFO 2020-08-02 04:21:50,103 basehttp 154 "GET /areas/340000/ HTTP/1.1" 200 837
INFO 2020-08-02 04:21:51,631 basehttp 154 "GET /areas/340200/ HTTP/1.1" 200 463
INFO 2020-08-02 04:22:24,001 basehttp 154 "OPTIONS /addresses/create/ HTTP/1.1" 200 0
INFO 2020-08-02 04:22:24,040 basehttp 154 "POST /addresses/create/ HTTP/1.1" 200 316
INFO 2020-08-02 04:22:24,368 basehttp 154 "GET /addresses/ HTTP/1.1" 200 527
INFO 2020-08-02 04:22:24,384 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 09:55:41,528 basehttp 154 "GET /addresses/ HTTP/1.1" 200 527
INFO 2020-08-02 09:55:41,556 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 10:16:06,876 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-08-02 10:16:09,987 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 10:16:15,985 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 10:16:16,037 basehttp 154 "GET /addresses/ HTTP/1.1" 200 527
INFO 2020-08-02 10:16:18,771 basehttp 154 "OPTIONS /addresses/3/default/ HTTP/1.1" 200 0
INFO 2020-08-02 10:16:18,849 basehttp 154 "PUT /addresses/3/default/ HTTP/1.1" 200 73
INFO 2020-08-02 10:16:19,043 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 10:16:19,064 basehttp 154 "GET /addresses/ HTTP/1.1" 200 527
INFO 2020-08-02 10:16:21,565 basehttp 154 "OPTIONS /addresses/1/default/ HTTP/1.1" 200 0
INFO 2020-08-02 10:16:21,603 basehttp 154 "PUT /addresses/1/default/ HTTP/1.1" 200 73
INFO 2020-08-02 10:16:21,843 basehttp 154 "GET /addresses/ HTTP/1.1" 200 527
INFO 2020-08-02 10:16:21,845 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 10:16:27,371 basehttp 154 "PUT /addresses/3/default/ HTTP/1.1" 200 73
INFO 2020-08-02 10:16:27,539 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 10:16:27,557 basehttp 154 "GET /addresses/ HTTP/1.1" 200 527
INFO 2020-08-02 10:16:30,038 basehttp 154 "PUT /addresses/1/default/ HTTP/1.1" 200 73
INFO 2020-08-02 10:16:30,225 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 10:16:30,249 basehttp 154 "GET /addresses/ HTTP/1.1" 200 527
INFO 2020-08-02 10:16:38,227 basehttp 154 "PUT /addresses/3/default/ HTTP/1.1" 200 73
INFO 2020-08-02 10:16:38,430 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 10:16:38,465 basehttp 154 "GET /addresses/ HTTP/1.1" 200 527
INFO 2020-08-02 10:16:50,581 basehttp 154 "PUT /addresses/1/default/ HTTP/1.1" 200 73
INFO 2020-08-02 10:16:50,783 basehttp 154 "GET /addresses/ HTTP/1.1" 200 527
INFO 2020-08-02 10:16:50,797 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 10:17:17,814 basehttp 154 "GET /areas/340000/ HTTP/1.1" 200 837
INFO 2020-08-02 10:17:20,451 basehttp 154 "GET /areas/340200/ HTTP/1.1" 200 463
INFO 2020-08-02 10:17:32,003 basehttp 154 "OPTIONS /addresses/3/ HTTP/1.1" 200 0
INFO 2020-08-02 10:17:32,042 basehttp 154 "PUT /addresses/3/ HTTP/1.1" 200 326
INFO 2020-08-02 10:28:51,239 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-08-02 10:28:53,111 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 10:29:00,050 basehttp 154 "OPTIONS /addresses/1/title/ HTTP/1.1" 200 0
INFO 2020-08-02 10:29:00,092 basehttp 154 "PUT /addresses/1/title/ HTTP/1.1" 200 61
INFO 2020-08-02 10:29:09,038 basehttp 154 "PUT /addresses/1/title/ HTTP/1.1" 200 61
INFO 2020-08-02 10:29:28,369 basehttp 154 "PUT /addresses/1/title/ HTTP/1.1" 200 61
INFO 2020-08-02 11:47:15,115 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-08-02 11:47:17,678 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 11:49:45,466 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-08-02 11:49:45,508 basehttp 154 "GET /addresses/ HTTP/1.1" 200 547
INFO 2020-08-02 11:50:26,589 basehttp 154 "OPTIONS /password/ HTTP/1.1" 200 0
INFO 2020-08-02 11:50:26,911 basehttp 154 "PUT /password/ HTTP/1.1" 200 27
INFO 2020-08-02 11:50:30,685 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-08-02 11:50:30,921 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-08-02 11:50:44,103 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-08-02 11:50:44,871 log 228 Not Found: /carts/simple/
WARNING 2020-08-02 11:50:44,878 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5412
INFO 2020-08-02 11:53:31,364 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-08-02 11:53:33,754 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 11:54:22,876 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/contents/models.py changed, reloading.
INFO 2020-08-02 11:54:24,428 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 11:56:40,281 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-08-02 11:56:41,812 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 11:56:55,459 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2020-08-02 11:56:57,129 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 11:57:39,832 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/apps/goods/models.py changed, reloading.
INFO 2020-08-02 11:57:41,819 autoreload 597 Watching for file changes with StatReloader
INFO 2020-08-02 12:26:38,404 autoreload 217 /home/ubuntu/meiduo_mall/meiduo_mall/urls.py changed, reloading.
INFO 2020-08-02 12:26:41,037 autoreload 597 Watching for file changes with StatReloader
